[package]
name = "apnotes_bin"
version = "0.3.8"
authors = ["Philipp Hentschel <philipp@f1ndus.de>"]
autobins = false
build = "build.rs"

[dependencies]
log = "0.4"
clap = "3.0.0-beta.2"
clap_generate = "3.0.0-beta.2"
colored = "2"
serde_json = "1.0.56"
serde_derive = "1.0.114"
serde = "1.0.114"
diesel = { features = ["sqlite"], version =  "1.4.5"}
itertools = "0.10.0"
flexi_logger = "0.22.0"
man = "0.3.0"

apnotes_lib = { path = "../lib" }

[[bin]]
name = "backup"
path = "src/bin/backup.rs"

[[bin]]
name = "apnotes"
path = "src/bin/notes.rs"